[workspace.lints.rust]
unsafe_code = "forbid"
# unused = "allow" # For experimental dev.

[workspace]
resolver = "2"
members = [
  'reports/fletcher',
  'reports/golden_section',
  'reports/newton'
]
